apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp-service
  template:
    metadata:
      labels:
        app: nlp-service
    spec:
      containers:
      - name: nlp-service
        image: prateek662/nlp_service_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
